name: "Testing"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tox:
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Checkout
        uses: actions/checkout@v7
      #----------------------------------------------
      #  -----  install & configure uv  -----
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      #----------------------------------------------
      # install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: uv sync --all-groups
      #----------------------------------------------
      #    Run pytest
      #----------------------------------------------
      - name: Test with pytest
        run: uv run pytest
